### ISSUE TITLE
Convert mzML to imzML

### ISSUE THREAD

**Issue by tygrad** [AlanRace/imzMLConverter#15]
What is the command line to convert mzML to imzML

**Comment by pchaillo** [comment]
I get the exact same problem.

I tried : java -jar jimzMLConverter-2.1.1.jar imzML 20210922_H30.mzML --image-dimensions 33 43 

But I get the following error : 

C:\Users\Administrator\Documents\PAUL\jimzMLConverter-2.1.1>java -jar jimzMLConv
erter-2.1.1.jar imzML 20210922_H30.mzML --image-dimensions 33 43
Feb 21, 2024 10:47:41 AM com.alanmrace.jimzmlconverter.MainCommand convert
INFO: Converting file 20210922_H30.mzML
Feb 21, 2024 10:47:41 AM com.alanmrace.jimzmlconverter.MainCommand convert
INFO: Detected mzML file
Feb 21, 2024 10:47:41 AM com.alanmrace.jimzmlconverter.MainCommand convert
SEVERE: No coordinates .txt file supplied for the 0th file 20210922_H30.mzML
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String ind
ex out of range: -1
        at java.lang.String.substring(Unknown Source)
        at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:115)
        at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:119)
        at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:119)
        at com.alanmrace.jimzmlparser.obo.OBO.loadOntologyFromFile(OBO.java:252)

        at com.alanmrace.jimzmlparser.obo.OBO.getOBO(OBO.java:169)
        at com.alanmrace.jimzmlconverter.ImzMLConverter.getOBOTerm(ImzMLConverte
r.java:209)
        at com.alanmrace.jimzmlconverter.ImzMLConverter.<init>(ImzMLConverter.ja
va:95)
        at com.alanmrace.jimzmlconverter.MzMLToImzMLConverter.<init>(MzMLToImzML
Converter.java:67)
        at com.alanmrace.jimzmlconverter.MainCommand.convert(MainCommand.java:30
2)
        at com.alanmrace.jimzmlconverter.MainCommand.main(MainCommand.java:186)
