### ISSUE TITLE
How can I convert the raw

### ISSUE THREAD

**Issue by QQhuan** [AlanRace/imzMLConverter#17]

**Comment by QQhuan** [comment]
Dear AlanRace, 
    I have a dataset, which from Thermo data, I want to got the imzML data by using this tools. What command should I input?
    My command and the errors are as follows:
    
    java -jar jimzMLConverter-2.1.1.jar imzML --image-dimensions 200 2
00 -o "E:\mass_spectrum_data\DGC\imzML" "E:\mass_spectrum_data\DGC\20210414\GC072N_DGC_83892_E001213_F1_R1.raw"

   4月 21, 2024 5:13:22 下午 com.alanmrace.jimzmlconverter.MainCommand convert
信息: Converting file E:\\mass_spectrum_data\\DGC\\20210414\\GC072N_DGC_83892_E001213_F1_R1.raw
4月 21, 2024 5:13:22 下午 com.alanmrace.jimzmlconverter.MainCommand generatemzMLFiles
信息: Detected Thermo RAW file
Checking for latest version of ProteoWizard in C:\Users\A\AppData\Local\Apps
"C:\Program Files\ProteoWizard\ProteoWizard 3.0.24100.098a63b\msconvert.exe" "E:\\mass_spectrum_data\\DGC\\20210414\\GC072N_DGC_83892_E001213_F1_R1.raw" --zlib --simAsSpectra --srmAsSpectra  -o "E:\\mass_spectrum_data\\DGC\\imzML"
format: mzML
    m/z: Compression-Zlib, 64-bit
    intensity: Compression-Zlib, 32-bit
    rt: Compression-Zlib, 64-bit
ByteOrder_LittleEndian
 indexed="true"
outputPath: E:\\mass_spectrum_data\\DGC\\imzML
extension: .mzML
contactFilename:
runIndexSet:

spectrum list filters:

chromatogram list filters:

filenames:
  E:\\mass_spectrum_data\\DGC\\20210414\GC072N_DGC_83892_E001213_F1_R1.raw

processing file: E:\\mass_spectrum_data\\DGC\\20210414\GC072N_DGC_83892_E001213_F1_R1.raw
calculating source file checksums

writing output file: E:\\mass_spectrum_data\\DGC\\imzML\GC072N_DGC_83892_E001213_F1_R1.mzML

4月 21, 2024 5:14:14 下午 com.alanmrace.jimzmlconverter.MainCommand convert
严重: No .udp or .txt file supplied for the 0th file E:\\mass_spectrum_data\\DGC\\20210414\\GC072N_DGC_83892_E001213_F1_R1.raw so assuming non-imaging data
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 50
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4608)
        at java.base/java.lang.String.substring(String.java:2711)
        at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:115)
        at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:119)
        at com.alanmrace.jimzmlparser.obo.OBO.<init>(OBO.java:119)
        at com.alanmrace.jimzmlparser.obo.OBO.loadOntologyFromFile(OBO.java:252)
        at com.alanmrace.jimzmlparser.obo.OBO.getOBO(OBO.java:169)
        at com.alanmrace.jimzmlconverter.ImzMLConverter.getOBOTerm(ImzMLConverter.java:209)
        at com.alanmrace.jimzmlconverter.ImzMLConverter.<init>(ImzMLConverter.java:95)
        at com.alanmrace.jimzmlconverter.MzMLToImzMLConverter.<init>(MzMLToImzMLConverter.java:67)
        at com.alanmrace.jimzmlconverter.ThermoMzMLToImzMLConverter.<init>(ThermoMzMLToImzMLConverter.java:29)
        at com.alanmrace.jimzmlconverter.MainCommand.convert(MainCommand.java:265)
        at com.alanmrace.jimzmlconverter.MainCommand.main(MainCommand.java:186)
        
        Thank u for your attention!
