### ISSUE TITLE
errors messages - @ MS:1002435 and @ MS:1000747

### ISSUE THREAD

**Issue by vinhdanh** [AlanRace/imzMLConverter#2]
Hello, I am trying to convert ToF-SIMS data (.grd) to imzML using your jimzMLConverter-2.0.6 . However, I got only one file ( .imzML.ibdtmp file ) instead of  .imzMLand .ibd files when I use the command 

java -jar jimzMLConverter-2.0.6.jar imzML -p "D:\file.properties.txt" "D:\file.grd"

And then, fails to recognize some tags:

D:\imzMLconver\jimzMLConverter-2.0.6\jimzMLConverter\target>java -jar jimzMLConverter-2.0.6.jar imzML -p "D:\file.properties.txt" "D:\file.grd"
May 04, 2019 10:11:48 PM com.alanmrace.jimzmlconverter.MainCommand convert
INFO: Converting file D:\file.grd
May 04, 2019 10:11:48 PM com.alanmrace.jimzmlconverter.MainCommand convert
INFO: Detected ION-TOF GRD file
May 04, 2019 10:11:48 PM com.alanmrace.jimzmlparser.obo.OBOTerm parse
INFO: Unknown value-type encountered 'value-type:xsd\:dateTime "The allowed value-type for this CV term."' @ MS:1000747
May 04, 2019 10:11:48 PM com.alanmrace.jimzmlparser.obo.OBOTerm parse
INFO: Unknown value-type encountered 'value-type:xsd\:dateTime "The allowed value-type for this CV term."' @ MS:1002435
May 04, 2019 10:11:48 PM com.alanmrace.jimzmlconverter.MainCommand convert
INFO: Converting using (MS:1000576) no compression compression for m/z array
May 04, 2019 10:11:48 PM com.alanmrace.jimzmlconverter.ImzMLConverter convert
INFO: Generating base imzML
May 04, 2019 10:14:05 PM com.alanmrace.jimzmlconverter.ImzMLConverter convert
INFO: Generated base imzML

I am not sure what is wrong ,so could you fix it?

**Comment by RaveendraCW** [comment]
Hello,
When I was trying to convert some ion TOF 5 data (GRD file) to imzML format I had to face the same type of issue. Could you please have a look and fix this? The converter I used was jimzMLConverter-2.1.0. Thanks.
PS C:\Users\rcham\Documents\converter\jimzMLConverter-2.1.0\jimzMLConverter\target> java -jar .\jimzMLConverter-2.1.0.jar imzML -p '.\@user list.fe2420 p8913 spot 15-(+).properties.txt' '.\@user list.fe2420 p8913 spot 15-(+).itm.grd'
Feb 26, 2020 10:00:27 AM com.alanmrace.jimzmlconverter.MainCommand convert
INFO: Converting file .\@user list.fe2420 p8913 spot 15-(+).itm.grd
Feb 26, 2020 10:00:27 AM com.alanmrace.jimzmlconverter.MainCommand convert
INFO: Detected ION-TOF GRD file
Feb 26, 2020 10:00:29 AM com.alanmrace.jimzmlparser.obo.OBOTerm parse
INFO: Unknown value-type encountered 'value-type:xsd\:dateTime "The allowed value-type for this CV term."' @ MS:1000747
Feb 26, 2020 10:00:29 AM com.alanmrace.jimzmlparser.obo.OBOTerm parse
INFO: Unknown value-type encountered 'value-type:xsd\:dateTime "The allowed value-type for this CV term."' @ MS:1002435
Exception in thread "main" java.lang.NullPointerException
        at com.alanmrace.jimzmlconverter.GRDToImzMLConverter.setPropertiesFile(GRDToImzMLConverter.java:98)
        at com.alanmrace.jimzmlconverter.MainCommand.convert(MainCommand.java:287)
        at com.alanmrace.jimzmlconverter.MainCommand.main(MainCommand.java:186)
PS C:\Users\rcham\Documents\converter\jimzMLConverter-2.1.0\jimzMLConverter\target>

**Comment by AlanRace** [comment]
Hi both,
Would you be able to send me the data that is failing?

Thanks,

Alan

**Comment by vinhdanh** [comment]
Hello, I am glad to get your reply
My files are very large, so I uploaded them on google drive

1. file grd ( compressed to .egg file)- 11Gb 
https://drive.google.com/file/d/12Ux4ABwTxGvL4USulktREsOhnI5tyDgk/view?usp=sharing

2. The properties file (.txt)  and bmp file
https://drive.google.com/file/d/1nKgNdWr8QDK2cI0e6OmGg7DFkGV-vX9A/view?usp=sharing
https://drive.google.com/file/d/1NKx_Onl-FoLueGm6ACOFFxVepttuPVT0/view?usp=sharing
​
3. ALzip program to unzip the egg file
https://drive.google.com/file/d/1BIJqWM3WedVcmF23uS2hvU9vSWPnqsY8/view?usp=sharing


Even I upgraded my pc ( intel i7 and ram 64gb)and set java heap size around 50Gb (-Xmx 51,200m), the error message ( out of memory) still came after 6 hours . I also attached these error message to this email.

I hope to hear from you.

Best regards
Uyen
​
-----Original Message-----
