### ISSUE TITLE
Got problem installation imzMLConverter

### ISSUE THREAD

**Issue by weantony** [AlanRace/imzMLConverter#3]
Got following problem after double double clicking run.bat or command line. Anyone seen it before. JDK have been installed and re-installed. Attempts have been tries on win7sp1pro and win10. Outcomes are the same.

F:\OneDrive\****\imzML convertor\imzMLConverter_1.3>java -jar -Xmx1024m imzMLConverter.jar
Exception in thread "main" java.lang.RuntimeException: Unable to add the swt jar to the class path: F:\OneDrive\study material\Queens Taskforce\sciex staff\imzML convertor\imzMLConverter_1.3\swt\org.eclipse.swt.win32.win32.x86_64-4.3.jar
        at imzMLConverter.gui.SWTLoader.loadSwtJar(SWTLoader.java:76)
        at imzMLConverter.gui.SWTLoader.<init>(SWTLoader.java:11)
        at imzMLConverter.gui.SWTLoader.main(SWTLoader.java:18)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at imzMLConverter.gui.SWTLoader.loadSwtJar(SWTLoader.java:68)
        ... 2 more

**Comment by AlanRace** [comment]
I am not sure whether this issue is still relevant (I apologise for the delay), but could you let me know which OS and Java versions you are/were running?

P.S. version 1.3 is an old version of the converter - the newer versions available on this repository shouldn't suffer from this issue.

**Comment by weantony** [comment]
> I am not sure whether this issue is still relevant (I apologise for the delay), but could you let me know which OS and Java versions you are/were running?
> 
> P.S. version 1.3 is an old version of the converter - the newer versions available on this repository shouldn't suffer from this issue.

Hi Alan,

Thank you very much for your reply. The problem has been resolved already.

Best Regards,
Jian
